plugins {
    id "idea"
    id "jacoco"
    id "maven-publish"
    id "org.jreleaser" version "1.19.0"
    id "org.jetbrains.kotlin.jvm" version "1.9.25"
    id "org.jetbrains.kotlin.plugin.spring" version "1.9.25"
    id "org.jetbrains.kotlin.plugin.jpa" version "1.9.25"
    id "org.jetbrains.kotlin.kapt" version "1.9.25"
    id "io.spring.dependency-management" version "1.1.7"
    id "org.jlleitschuh.gradle.ktlint" version "12.3.0"
}

ext {
    springBootVersion = "3.5.10"
    testContainersVersion = "1.21.1"
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}

ktlint {
    version.set("1.1.1")
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
    }
}

[compileKotlin, compileTestKotlin]*.kotlinOptions*.jvmTarget = "17"

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-batch"
    implementation "org.springframework.boot:spring-boot-starter-data-jdbc"

    implementation "com.h2database:h2"
    implementation "org.postgresql:postgresql"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.testcontainers:postgresql:$testContainersVersion"
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = false
    }
}

check.dependsOn jacocoTestReport

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            pom {
                name = "data-migration-lib"
                description = "Database migration library based on Spring Batch"
                url = "https://github.com/Romanow/data-migration-lib/"
                licenses {
                    license {
                        name = "The MIT License"
                        url = "https://opensource.org/license/mit"
                    }
                }
                developers {
                    developer {
                        id = "Romanow"
                        name = "Romanov Alexey"
                        email = "romanow.tech@gmail.com"
                    }
                }
                scm {
                    url = "https://github.com/Romanow/data-migration-lib/"
                    connection = "scm:git:https://github.com/Romanow/data-migration-lib.git"
                    developerConnection = "scm:git:ssh://github.com/Romanow/data-migration-lib.git"
                }
            }
        }
    }
    repositories {
        maven {
            url = "build/staging-deploy"
        }
    }
}

jreleaser {
    signing {
        active = "ALWAYS"
        armored = true
    }
    deploy {
        maven {
            mavenCentral {
                sonatype {
                    active = "ALWAYS"
                    url = "https://central.sonatype.com/api/v1/publisher"
                    stagingRepository("build/staging-deploy")
                }
            }
        }
    }
}
